"""bakerystockmodel

Revision ID: 4a2fee7be16f
Revises: 
Create Date: 2022-01-19 03:58:13.306630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a2fee7be16f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('errorlogs',
    sa.Column('err_class', sa.String(), nullable=True),
    sa.Column('err_resource', sa.String(), nullable=True),
    sa.Column('err_msg', sa.String(), nullable=True),
    sa.Column('app_stamp', sa.TIMESTAMP(), nullable=True),
    sa.Column('db_stamp', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('tbl_id', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('tbl_id')
    )
    op.create_table('location',
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('department', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('subcategory', sa.Text(), nullable=True),
    sa.Column('location_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('db_stamp', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('location_id')
    )
    op.create_table('sku',
    sa.Column('sku', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('department', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('subcategory', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('sku')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sku')
    op.drop_table('location')
    op.drop_table('errorlogs')
    # ### end Alembic commands ###
